collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7297286870889366
  brandStrength: 0.7680851
  lightness: 0.1910088260192424
  brandColors:
    - '#F1E9D4'
    - '#71B3B3'
    - '#BB1E1D'
    - '#988465'
    - '#030003'
  rhythmicContrast: 0.9234288525767624
typography_spectrum: 0.5340425
layout_spectrum: 1
name: The New Town
